# Generated by Django 3.0.8 on 2020-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='vision_photos/', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', help_text='Profile Picture', upload_to='vision_profile', verbose_name='Profile Picture')),
                ('image_height', models.PositiveIntegerField(blank=True, default='400', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='400', editable=False, null=True)),
            ],
        ),
    ]
