# Generated by Django 3.0.5 on 2020-05-01 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', help_text='Profile Picture', upload_to='vision_profile', verbose_name='Profile Picture')),
                ('image_height', models.PositiveIntegerField(blank=True, default='400', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='400', editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='vision_photos/')),
                ('vision', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Vision')),
            ],
        ),
    ]
