# Generated by Django 3.0.5 on 2020-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='vision_photos/', verbose_name='Photo'),
        ),
    ]
