# Generated by Django 3.0.5 on 2020-05-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200501_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='vision',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Vision'),
        ),
    ]
