# Generated by Django 3.0.5 on 2020-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200501_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title2',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
    ]
