# Generated by Django 3.0.5 on 2020-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_photo_title2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title2',
            field=models.CharField(blank=True, default='DEFAULT', max_length=20, null=True),
        ),
    ]
