# Generated by Django 3.0.5 on 2020-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200501_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Profile Picture', null=True, upload_to='vision_profile', verbose_name='Profile Picture'),
        ),
    ]
