# Generated by Django 3.0.5 on 2020-05-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200508_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='image_width',
        ),
    ]
