# Generated by Django 3.0.5 on 2020-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200508_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Profile Picture', upload_to='vision_profile', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='vision',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='400', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='400', editable=False, null=True),
        ),
    ]
