# Generated by Django 3.0.5 on 2020-05-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200508_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title2',
        ),
    ]
