# Generated by Django 3.0.5 on 2020-05-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
    ]
