# Generated by Django 3.0.8 on 2020-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20200801_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Profile Picture', upload_to='https://vision-board-django-amit.s3.ap-south-1.amazonaws.com/', verbose_name='Profile Picture'),
        ),
    ]
