# Generated by Django 3.0.8 on 2020-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20200820_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vision',
            name='image',
            field=models.ImageField(default='default.jpg', help_text='Profile Picture', upload_to='vision_profile', verbose_name='Profile Picture'),
        ),
    ]
